mash-up-kr/SulSul-Android

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/theme/Typography.kt

#12 타이포그라피 정의

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/component/SulSulButton.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/component/model/SulSulButtonColor.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/component/model/SulSulButtonSize.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/component/model/SulSulIconOnlyButtonSize.kt

뭔가  SulSulButtonSize enum 클래스 쪽에서 패딩관련이나 radius를 분리해도 좋을것 같다고 생각했는데 크기 관련인거 같아서 일단은 다 같이 넣어 놨습니다. 이 부분 뭔가 별로면 말씀해 주세여ㅎ 컴포저블 함수에 최대한 파라미터를 적게 전달하고 싶은 마음이었습니다..ㅎ

#25 [공통] 공통 버튼 개발 

---

presentation/src/main/res/values/strings.xml

#43 [로그인] strings 추가

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/component/SulSulBadge.kt

- middle badge 텍스트 스타일 : SubTitle3 -> SubTitle4

#36 [공통] middle badge 텍스트 크기 변경

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/measure_result/MeasureResultScreen.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/component/SulSulBadge.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/theme/Color.kt

- SubPurple16 -> 색상명만 변경
- White40 -> 색상명, 색상값 변경사항 적용

#42 [공통] 디자인 시스템 추가된 색상으로 수정

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/component/WebView.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measuring/MeasuringScreen.kt

* 주량 측정 위치에 버블 컨테이너를 위치하기 위해 웹뷰 선언
* 웹뷰에 투명한 배경 적용

#38 [주량 측정] 버블 컨테이너가 들어갈 위치에 웹뷰 선언

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measuring/AlcoholSelection.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measuring/MeasuringActivity.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measuring/MeasuringScreen.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measuring/model/MeasuringState.kt

- 주종 변경 컴포넌트 본인 자리에 넣어드렸습니당
close #53

#53 [주량 측정] 주종 변경 컴포넌트 교체

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/component/EmptyPromiseCard.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/theme/Color.kt
presentation/src/main/res/drawable/ic_empty_promise.xml
presentation/src/main/res/values/strings.xml

close #56 
- 술약속이 없을 때 보여줄 컴포넌트입니다~
- 버튼 클릭 이벤트 연결해야 합니다!

#56 [홈] 술 약속 노데이터 컴포넌트

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/theme/Color.kt

#73 [공통] 누락된 그라디언트 컬러 추가

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/model/AlcoholPromiseCardState.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/model/AlcoholPromiseCardType.kt

#75 [홈] 술 약속 카드 위스키 추가 

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/model/AlcoholPromiseCardType.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/theme/Color.kt

+ 디자인 시스템이랑 이름 맞추도록 코드 수정했습니당~

#76 [홈] 술 약속 카드 그라디언트 컬러 수정 

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/HomeScreen.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/component/AlcoholPromiseCard.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/component/AlcoholTierCard.kt

close #78 
- 칭호 테두리 빼고 약속 테두리 넣었슴다

#78 [홈] 카드 테두리 수정

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measureresult/MeasureResultScreen.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measureresult/model/AlcoholType.kt
presentation/src/main/res/drawable/ic_whisky_s.xml

#85 [주량 측정] 위스키 아이콘 추가 

---

data/src/main/java/com/mashup/alcoholfree/data/datasource/MeasureDataSource.kt
data/src/main/java/com/mashup/alcoholfree/data/dto/remote/request/DrinkRequest.kt
data/src/main/java/com/mashup/alcoholfree/data/dto/remote/request/MeasureResultReportRequest.kt
data/src/main/java/com/mashup/alcoholfree/data/dto/remote/response/MeasureResultReportResponse.kt
data/src/main/java/com/mashup/alcoholfree/data/repository/MeasureRepositoryImpl.kt
data/src/main/java/com/mashup/alcoholfree/data/service/SulSulService.kt
domain/src/main/java/com/mashup/alcoholfree/domain/model/MeasureResultReportId.kt
domain/src/main/java/com/mashup/alcoholfree/domain/model/MeasureResultReportParam.kt
domain/src/main/java/com/mashup/alcoholfree/domain/repository/MeasureRepository.kt
domain/src/main/java/com/mashup/alcoholfree/domain/usecase/CreateMeasureResultReportUseCase.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/component/AlcoholPromiseCard.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/model/AlcoholPromiseCardState.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/model/Drink.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/model/DrinkUiModel.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/model/MeasureResultReportParamUiModel.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/login/LoginActivity.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measureresult/MeasureResultActivity.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measureresult/MeasureResultViewModel.kt

+ 주량 측정 보고서 생성 API 연결 완료 했습니다~

#59 [주량 측정] 주량 측정 보고서 생성 API 연결 

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measuring/AlcoholExceedDialog.kt
presentation/src/main/res/values/strings.xml

#89 [주량 측정] 본인 주량 넘었을 때 alert 구현 

---

buildSrc/src/main/java/Version.kt
data/src/main/java/com/mashup/alcoholfree/data/datasource/PromiseDataSource.kt
data/src/main/java/com/mashup/alcoholfree/data/di/RepositoryModule.kt
data/src/main/java/com/mashup/alcoholfree/data/dto/remote/response/CardResponse.kt
data/src/main/java/com/mashup/alcoholfree/data/dto/remote/response/PromiseCardsResponse.kt
data/src/main/java/com/mashup/alcoholfree/data/repository/PromiseRepositoryImpl.kt
data/src/main/java/com/mashup/alcoholfree/data/service/SulSulService.kt
domain/src/main/java/com/mashup/alcoholfree/domain/model/PromiseCard.kt
domain/src/main/java/com/mashup/alcoholfree/domain/repository/PromiseRepository.kt
domain/src/main/java/com/mashup/alcoholfree/domain/usecase/GetAlcoholPromiseCardsUseCase.kt
presentation/build.gradle.kts
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/HomeActivity.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/HomeScreen.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/HomeViewModel.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/component/AlcoholPromiseCard.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/model/AlcoholPromiseCardState.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/model/AlcoholPromiseCardType.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/model/AlcoholPromiseCardUiModel.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/model/AlcoholTier.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/model/Drink.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/model/DrinkUiModel.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/model/HomeState.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/utils/DateFormatter.kt

#57 [홈] 술약속 카드 조회 API 연결

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measureresult/MeasureResultActivity.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measureresult/MeasureResultScreen.kt
presentation/src/main/res/drawable/ic_alcohol.xml

* 홈으로 돌아가기 버튼 기능 추가
* 평균 도수 아이콘 추가
아~주 깔끔합니다잉

#96 주량 측정 화면 UI 미구현 기능 추가

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/component/SulSulBackButton.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/component/SulSulButton.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measuring/AlcoholBackPressDialog.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measuring/MeasuringActivity.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measuring/MeasuringScreen.kt
presentation/src/main/res/values/strings.xml

#106 [주량 측정] 뒤로가기 클릭 시 다이얼로그 

---

data/src/main/java/com/mashup/alcoholfree/data/datasource/MyInfoDataSource.kt
data/src/main/java/com/mashup/alcoholfree/data/dto/remote/request/RegisterTierRequest.kt
data/src/main/java/com/mashup/alcoholfree/data/dto/remote/response/RegisterDrinkingLimitResponse.kt
data/src/main/java/com/mashup/alcoholfree/data/repository/MyInfoRepositoryImpl.kt
data/src/main/java/com/mashup/alcoholfree/data/service/SulSulService.kt
domain/src/main/java/com/mashup/alcoholfree/domain/model/RegisterTierParam.kt
domain/src/main/java/com/mashup/alcoholfree/domain/repository/MyInfoRepository.kt
domain/src/main/java/com/mashup/alcoholfree/domain/usecase/RegisterDrinkingLimitUseCase.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/HomeActivity.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/register/RegisterTierActivity.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/register/RegisterTierViewModel.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/utils/EventWrapper.kt

#110 [주량 등록] 주량 등록 API 연결

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/component/WebView.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measuring/AlcoholSelection.kt

+ 수정완료..ㅎ 클릭 이벤트를 뺏어 올려고 주종 선택 부분에 아무 동작하지 않는 clickable을 달았습니다. ripple 효과도 없앴습니다.. 너무 야매라면 다시 고민해 볼게용..ㅎ

 #116 [주량 측정] 웹뷰 전체 터치 이벤트 수정

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measuring/MeasuringScreen.kt

#115 [주량 측정] 네비게이션 바에 있는 백 버튼 다이얼로그 구현 

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/register/RegisterTierActivity.kt

- close #126 
- 뒤로가기 누르면 온보딩 웹뷰를 닫습니다

#126 [주량 등록] 웹뷰 뒤로가기 버튼 추가

---

data/src/main/java/com/mashup/alcoholfree/data/dto/remote/response/CardResponse.kt
domain/src/main/java/com/mashup/alcoholfree/domain/model/PromiseCard.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/component/AlcoholPromiseCard.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/model/AlcoholPromiseCardState.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/model/AlcoholPromiseCardUiModel.kt

#124 [홈] 카드 칭호 추가 

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measureresult/MeasureResultScreen.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measureresult/MeasureResultViewModel.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measureresult/model/AlcoholType.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measureresult/model/MeasureResultState.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/measureresult/model/MeasureResultUiModel.kt

- close #128 
위스키 출력 조건을 고량주로 걸어서 위스키가 출력이 안되는 이슈가 있더라구여..? 
헷갈리기도 하고 해서 그냥 리스트로 바꿔버렸습니다

#128 [측정 결과] 위스키 출력 안되는 이슈

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/login/LoginActivity.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/login/LoginViewModel.kt

#138 [로그인] 로그인 성공 했을때 이벤트 추가 

---

presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/HomeActivity.kt
presentation/src/main/java/com/mashup/alcoholfree/presentation/ui/home/HomeViewModel.kt

#145 style: 동기적인 코드 추가
